---
title: "Sistema de Referencia y contrareferencia"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#F0FDFA"
      fg: "#1E2939" 
      primary: "#93E5D5"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
    
    navbar:
      - title: "Reporte"
        href: "./reportes/PracticoN1_Ramos_Roa.html"
        
    social: ["menu"]
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(sf)
library(leaflet)
library(readxl)
library(readr)
library(xtable)
library(knitr)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(DT)
library(tidyverse)
library(shiny)
library(plotly)

# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

```{r, echo = FALSE, include = FALSE}
regiones <- st_read("files/regiones/regiones.shp")
establecimientos <- st_read("files/establecimientos/establecimientos.shp")
regiones <- mutate(regiones,colorfondo=case_when(
  region=="Región de la Comarca"~"red",
  region=="Región Confluencia"~"blue",
  region=="Región del Limay"~"yellow",
  region=="Región Alto Neuquén"~"orange",
  region=="Región de los Lagos del Sur"~"green",
  region=="Región Vaca Muerta"~"purple",
  region=="Región del Pehuén"~"violet"
))

# Creamos un ícono personalizado más chico (ej: 15x25 píxeles)
icono_chico <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png",
  iconWidth = 15,   # Ancho del marcador en píxeles
  iconHeight = 25,  # Alto del marcador en píxeles
  iconAnchorX = 7,  # Punto de anclaje horizontal (mitad del ancho)
  iconAnchorY = 25  # Punto de anclaje vertical (base del pin)
)

establecimientos <- establecimientos %>%
  mutate(popup = paste0(
    "<h4>", fna, "</h4>",
    "Tipo de establecimiento: ", gna, "<br>",
    "Complejidad: ", complej, "<br>"
  ))

mapa_base_IGNG <- leaflet()%>% 
  addTiles('https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/{z}/{x}/{-y}.png') %>%
  setView(lng =-68.140642,lat =-38.805236, zoom = 7) %>%  
  addWMSTiles(
    "https://wms.ign.gob.ar/geoserver/capabaseargenmap/gwc/service/wmts?request=GetCapabilities",
    layers= "Capa base Argenmap",
    options = WMSTileOptions(format = "image/png", transparent = TRUE),
    tileOptions(tms = TRUE),
    attribution = '<a href="http://www.ign.gob.ar/AreaServicios/Argenmap/IntroduccionV2" target="_blank">Instituto Geográfico Nacional</a> + <a href="http://www.osm.org/copyright" target="_blank">OpenStreetMap</a>') %>%  
addPolygons(
    data = regiones,
    color = "blue",
    weight = 2,
    fillColor = ~colorfondo,
    fillOpacity = 0.3,
    group="Regiones Sanitarias"
  ) %>%
 addMarkers(data=establecimientos,
            icon = icono_chico, 
            popup=~popup,
            group="Establecimientos")%>% 
 addLayersControl(overlayGroups = c("Regiones Sanitarias","Establecimientos"))%>%
 addLegend(
    position = "bottomright",
    colors = regiones$colorfondo,
    labels = regiones$region,
    title = "Regiones Sanitarias"
  )


```

Regionalización
============================================

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Mapa Regionalización

```{r, echo = FALSE}
    
mapa_base_IGNG

```

### Establecimientos

#### Distribución de establecimiento por tipo
```{r,echo=FALSE}
gTiposEstablecimientos <- ggplot(establecimientos, aes(x = factor(gna))) +
  geom_bar(fill = "#548FC4", color = "white", width = 0.6) +
  labs(
    x = "Tipo de establecimiento",
    y = NULL
  ) +
  theme_minimal(paper="#F0FDFA") +
theme(
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      vjust = 1
    )
  
)
ggplotly(gTiposEstablecimientos) %>%
  layout(
    paper_bgcolor = "#F0FDFA",
    plot_bgcolor = "#F0FDFA",
    xaxis = list(showgrid = FALSE),
    yaxis = list(showgrid = TRUE)
  )


```
<br>
<br>
<br>

#### Distribución de los Efectores por nivel de complejidad

```{r,echo=FALSE}
gComplejidad <- ggplot(establecimientos, aes(x = factor(complej))) +
  geom_bar(fill = "#E28A78", color = "white", width = 0.6) +
  labs(
    x = "Nivel de Complejidad",
    y = "Frecuencia"
  ) +
  theme_minimal(paper="#F0FDFA")

ggplotly(gComplejidad) %>%
  layout(
    paper_bgcolor = "#F0FDFA",
    plot_bgcolor = "#F0FDFA",
    xaxis = list(showgrid = FALSE),
    yaxis = list(showgrid = TRUE)
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Cantidad de establecimientos

```{r,echo=FALSE}
cantEstablecimiento <- nrow(establecimientos)
valueBox(cantEstablecimiento, icon="fa-hospital", color="info")
``` 

### Cantidad de Regiones

```{r,echo=FALSE}
cantRegiones <- nrow(regiones)
valueBox(cantRegiones, icon="fa-globe-americas", color="warning")
```


### Distribución de establecimientos por región

```{r, echo = FALSE}
establecimientosRegion <- st_join(establecimientos, regiones, join = st_intersects)

  
Datos_agrupados<-establecimientosRegion%>%
    group_by(region)%>%
    summarise(cantidad = n())


ggplot(Datos_agrupados,
       aes(x = reorder(region, cantidad), y = cantidad)) +
  geom_col(fill = "#FFDA8A", width = 0.7,) +
  geom_text(
    aes(label = cantidad),
    hjust = 1.2,
    color = "black",
    size = 3.5,
    fontface = "bold"
  ) +
  coord_flip() +
  theme_minimal(paper="#F0FDFA")+
  labs(x = NULL, y = NULL) +
  theme(
    axis.text = element_text(size = 10)
  ) +
  expand_limits(y = max(Datos_agrupados$cantidad) * 1.1)

```




Derivaciones
============================================


```{r, echo=FALSE}

datos_solicitudes <- read_csv("files/listado-solicitudes_2026.csv")

datos_solicitudes <- select(datos_solicitudes,-idPrestacion,-idPaciente)
datos_solicitudes$EfectorSISAOrigen <- as.character(datos_solicitudes$EfectorSISAOrigen)
datos_solicitudes$EfectorSISADestino <- as.character(datos_solicitudes$EfectorSISADestino)



datos_solicitudes <- mutate(datos_solicitudes,
                             finalizada=ifelse(estadoActual=="validada" | estadoActual=="rechazada" | estadoActual=="vencida" ,TRUE,FALSE))

# Vamos a calcular el tiempo de demora de la solicitudes en días:
# Para las finalizadas el tiempo de demora es la diferencia entre la fecha de inicio y la fecha del estado actual
# Para las que no estan finalizadas el tiempo se calcula con fecha de inicio y la fecha actual

datos_solicitudes$fechaInicio <- as.POSIXct(datos_solicitudes$fechaInicio, format = "%d-%m-%Y %H:%M")
datos_solicitudes$fechaEstadoActual <- as.POSIXct(datos_solicitudes$fechaEstadoActual, format = "%d-%m-%Y %H:%M")

datos_solicitudes <- mutate(datos_solicitudes, diasPasados = ifelse(datos_solicitudes$finalizada, 
           round(as.numeric(
               difftime(datos_solicitudes$fechaEstadoActual, datos_solicitudes$fechaInicio, units = "days"))), 
           round(as.numeric(
               difftime(Sys.time(), datos_solicitudes$fechaInicio, units = "days")))))



```



```{r, echo=FALSE}
# Unir establecimientos con regiones: Le pega a cada punto el nombre de la región sanitaria a la que pertenece

establecimientos_con_region <- st_join(establecimientos, regiones, join = st_intersects)

coords <- st_coordinates(establecimientos)

# Extraemos las coordenadas X e Y de todos los establecimientos para poder cruzarlas

coords_establecimientos <- establecimientos_con_region %>%
  mutate(
    X = coords[,1],
    Y = coords[,2]
  ) %>%
  st_drop_geometry() %>%
  select(cod_sisa, X, Y, region)
```



```{r,echo=FALSE}
# Cruzamos los datos de derivaciones con los datos geograficos
# Cruzamos por el Origen
deriv_con_coords <- datos_solicitudes %>%
  left_join(coords_establecimientos, by = c("EfectorSISAOrigen" = "cod_sisa")) %>%
  rename(X_orig = X, Y_orig = Y, Region_orig = region) %>%
  
  left_join(coords_establecimientos, by = c("EfectorSISADestino" = "cod_sisa")) %>%
  rename(X_dest = X, Y_dest = Y, Region_dest = region) %>%
  
  #Limpiamos registros sin coordenadas válidas
  filter(!is.na(X_orig) & !is.na(X_dest)) %>%
  
  # Contamos cuántas derivaciones existen por par Origen-Destino
  # Incluimos las coordenadas y variables categóricas que queramos conservar para el mapa
  group_by(EfectorOrigen, EfectorSISAOrigen,Region_orig, EfectorDestino,EfectorSISADestino, Region_dest, X_orig, Y_orig, X_dest, Y_dest) %>%
  summarise(
    cantidad_solicitudes = n(),
    .groups = "drop"
  )



```
  
Column {data-width=200}
----------------------------------------------------  
### Mapa interactivo

```{r,echo=FALSE}
#Elegimos la region que se mostrará en el mapa
selectInput(
  "region",
  "Región sanitaria",
  choices = sort(unique(regiones$region)),
  selected = ""
)

```



### Derivaciones origen

```{r,echo=FALSE}

derivaciones_region_orig<- reactive({
  deriv_con_coords %>%
    filter(Region_orig == input$region)%>%
    summarise(total = sum(cantidad_solicitudes, na.rm = TRUE)) %>%
    pull(total)
})

output$cant_derivaciones_region_orig <- renderValueBox({
   valueBox(
    value = derivaciones_region_orig(),
    caption = paste("Derivaciones originadas en ", input$region, sep = "\n"),
    icon="fa-sign-out",
    color="info"
  ) 
})

``` 

```{r}
valueBoxOutput("cant_derivaciones_region_orig")
```

### Derivaciones destino

```{r,echo=FALSE}

derivaciones_region_dest<- reactive({
  deriv_con_coords %>%
    filter(Region_dest == input$region)%>%
    summarise(total_dest = sum(cantidad_solicitudes, na.rm = TRUE)) %>%
    pull(total_dest)
})

output$cant_derivaciones_region_dest <- renderValueBox({
   valueBox(
    value = derivaciones_region_dest(),
    
    caption = paste("Derivaciones recibidas en ", input$region, sep = "\n"),
    icon="fa-sign-in",
    color="warning"
  ) 
})
```


```{r}
valueBoxOutput("cant_derivaciones_region_dest")
```

### Promedio de días de espera

```{r, echo=FALSE}
gauge(
  value = round(mean((datos_solicitudes$diasPasados))),
  min = 0,
  max = 250,
  sectors = gaugeSectors(
    success = c(0, 60),
    warning = c(61, 120),
    danger = c(121, 250)
  )
)
```


Column {data-width=600}
----------------------------------------------------
###

```{r, echo=FALSE}

#filtramos el poligono de la región seleccionada
region_poligono <- reactive({
  regiones %>%
    filter(region == input$region)
})

#filtra las los establecimientos de la region seleccionada
establecimientos_region <- reactive({
  establecimientos_con_region %>%
    filter(region == input$region)
})

#filtra las derivaciones cuyo origen sean establecimientos de la región seleccionada
deriv_filtradas <- reactive({
  deriv_con_coords %>%
    filter(EfectorSISAOrigen %in%
             establecimientos_region()$cod_sisa)

})


# FILTRAR DERIVACIONES QUE SE ORIGINAN EN LA REGIÓN SELECCIONADA
# Filtramos para que el origen de la derivación esté en la lista de establecimientos de la región
deriv_lineas_sf <- reactive({
  lineas_deseo_list <- lapply(
    1:nrow(deriv_filtradas()),
    function(i){
      st_linestring(
        matrix(
          c(
            deriv_filtradas()$X_orig[i],
            deriv_filtradas()$X_dest[i],
            deriv_filtradas()$Y_orig[i],
            deriv_filtradas()$Y_dest[i]
          ),
          ncol = 2
        )
      )
    })
  st_sf(
    deriv_filtradas(),
    geometry = st_sfc(
      lineas_deseo_list,
      crs = st_crs(establecimientos)
    )
  )
})


# Cartelito interactivo para las líneas de derivación
deriv_lineas_geo <- reactive({ deriv_lineas_sf() %>%
  mutate(popup_texto = paste0(
    "<strong>Flujo de Derivación</strong><br/>",
    "<strong>Origen SISA:</strong> ", EfectorOrigen, "<br/>",
    "<strong>Destino SISA:</strong> ", EfectorDestino, "<br/>",
    "<strong>Total Solicitudes:</strong> <span style='color:red;'>", cantidad_solicitudes, "</span>"
  ))
})

# Cartelito interactivo para cada punto (establecimiento)
establecimientos_region_geo <- reactive({ establecimientos_region() %>%
  mutate(popup_texto = paste0(
    "<strong>Establecimiento:</strong> ", fna, "<br/>",
    "<strong>Tipo:</strong> ", gna, "<br/>",
    "<strong>Código SISA:</strong> ", cod_sisa
  ))
})

output$mapa <- renderLeaflet({

  leaflet() %>%
     addTiles('https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/{z}/{x}/{-y}.png') %>%
    setView(lng =-70.0654592747529,lat =-38.901926288446575, zoom = 7) %>%
    addWMSTiles(
    "https://wms.ign.gob.ar/geoserver/capabaseargenmap/gwc/service/wmts?request=GetCapabilities",
    layers= "Capa base Argenmap",
    options = WMSTileOptions(format = "image/png", transparent = TRUE),
    tileOptions(tms = TRUE),
    attribution = '<a href="http://www.ign.gob.ar/AreaServicios/Argenmap/IntroduccionV2" target="_blank">Instituto Geográfico Nacional</a> + <a href="http://www.osm.org/copyright" target="_blank">OpenStreetMap</a>') %>%
  
    addPolygons(
      data = region_poligono(),
      fillColor = "orange",
      fillOpacity = 0.3,
      color = "#666666",
       weight = 1.5,
      group = "region"
    ) %>%

    addPolylines(
      data = deriv_lineas_geo(),
         # El grosor físico en la pantalla depende de la cantidad de solicitudes
      weight = ~sqrt(cantidad_solicitudes) * 1.5, 
      color = "#1f78b4",
      opacity = 0.7,
   # highlightOptions = highlightOptions(weight = 5, color = "#ff7f00", bringToFront = TRUE),
      popup = ~popup_texto,
      group = "Líneas de Derivación"
    ) %>%

    addCircleMarkers(
      data = establecimientos_region_geo(),
      radius = 6,
      fillColor = "#e31a1c",
      fillOpacity = 0.9,
      color = "#ffffff",
      weight = 1,
      popup = ~popup_texto,
      group = "Establecimientos"
    )

})


# 4. VISUALIZAR EL MAPA EN RSTUDIO
leafletOutput("mapa", height =  700)

```



```{r,  echo=FALSE}
#mejoras
# revisar input debajo agregar box reactivos por la región elegida
# lineas: cambios para poder diferencialas mejor
# clouster para los puntos (o lineas)
# agregar listados

# el mapa interactivo responde a "cómo es el transito de pacientes dentro del sistema público de salud dentro de una región y hacia afuera de la misma"

```


